trigger: 
  branches:
   include:
     - master

pool:
  name: Hosted Ubuntu 1604

variables:
    azureSubscriptionEndpoint: CDAYS19
    CONTAINER_REGISTRY_ADDRESS: 'cdays19faceoff.azurecr.io'
    CONTAINER_REGISTRY_USERNAME: 'CDAYS19FaceOff'

steps:
- script: docker run --rm --privileged multiarch/qemu-user-static:register --reset

- task: AzureIoTEdge@2
  displayName: 'Azure IoT Edge - Build module images'
  name: 'build_images'
  inputs:
    defaultPlatform: arm32v7

- task: AzureIoTEdge@2
  displayName: 'Azure IoT Edge - Push module images'
  name: 'publish_images'
  inputs:
    action: 'Push module images'
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(CONTAINER_REGISTRY_ADDRESS)
    defaultPlatform: arm32v7
  continueOnError: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$[build_images.DEPLOYMENT_FILE_PATH]'